{
 "title": "Vector stats",
 "description": "Dashboard for base internal vector metrics.\r\n\r\ninputs, dedupe stats, synks",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Processed events (avg 5 min)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(vector_processed_events_total{component_kind=\"source\",component_name!=\"metrics_id\"}[5m])",
     "legendFormat": "{{ component_name }}"
    }
   ]
  },
  {
   "title": "Events by source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(vector_events_in_total{component_kind=\"source\"}[5m])) by (component_name)",
     "legendFormat": "{{ component_name }}"
    }
   ]
  },
  {
   "title": "Requests received ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector_requests_received_total", "legendFormat": "{{ component_id }}" }
   ]
  },
  {
   "title": "Eevents by sink",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(vector_events_out_total{component_kind=\"sink\",component_name!=\"sync_metrics_id\"}[5m])) by (component_name)",
     "legendFormat": "{{ component_name }}"
    }
   ]
  },
  {
   "title": "Dedupe rate (avg 5 min)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(vector_events_discarded_total{component_kind=\"transform\",component_type=\"dedupe\"}[5m])"
    }
   ]
  }
 ]
}